# Dependabot configuration file.
version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: ".github/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: *
        update-types:
          - "version-update:semver-patch"
