name: Request a cherry-pick (for contributors use only).
description: Request a patch to be cherry-picked into a release.
title: '[CP] <title>'
labels: ['cherry-pick-review']

assignees:
  - mit-mit
  - athomas
  - vsmenon
  - itsjustkevin

body:
  - type: textarea
    id: commit_hash
    attributes:
      label: Commit(s) to merge
      description: What are the changelist(s) that have been merged to main?
    validations:
      required: true
  - type: input
    id: target
    attributes:
      label: Target
      description: Should the changes be cherry-picked to beta, stable, or both?
    validations:
      required: true
  - type: input
    id: changelist
    attributes:
      label: Prepared changelist for beta/stable
      description: Gerrit changelist(s) against beta and/or stable per https://github.com/dart-lang/sdk/tree/main/docs/Cherry-picks-to-a-release-channel.md
    validations:
      required: true
  - type: textarea
    id: issue_description
    attributes:
      label: Issue Description
      description: Brief description of the issue. What is the issue? What platforms are the problems occurring on?
    validations:
      required: true
  - type: textarea
    id: fix
    attributes:
      label: What is the fix
      description: Brief description of the fix.
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why cherry-pick
      description: Describe the reasons, impacted users and functional issues to explain why this should be cherry-picked.
    validations:
      required: true
  - type: textarea
    id: risk
    attributes:
      label: Risk
      description: What is the risk level of this cherry-pick?
    validations:
      required: true
  - type: input
    id: original_issue
    attributes:
      label: Issue link(s)
      description: Add links to the original issues fixed by this cherry-pick
    validations:
      required: true
  - type: textarea
    id: extra_info
    attributes:
      label: Extra Info
      description: Is there anything else we need to know about this cherry-pick?
