name: Propose a breaking change (for contributors use only).
description: Initiate a breaking change process.
title: '[breaking change] <title>'
labels: ['breaking-change-request']

assignees:
  - itsjustkevin
  - kevmoo

body:
  - type: textarea
    id: change_intent
    attributes:
      label: Change Intent
      description: What is the intent of this change?
  - type: textarea
    id: justification
    attributes:
      label: Justification
      description: What is the justification for this change?
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: What is the impact of this change?
  - type: textarea
    id: mitigation
    attributes:
      label: Mitigation
      description: How can we mitigate the impact?
  - type: textarea
    id: change_timeline
    attributes:
      label: Change Timeline
      description: What is the expected timeline for deprecation / removal?
  - type: textarea
    id: associated_cls
    attributes:
      label: Associated CLs
      description: Which CLs are in progress or have already landed to accomplish this change?
